- README.md
- dktk-fed/docker-compose.yml
- lib/add_bc_user.sh
- lib/generate.sh
- lib/prerequisites.sh
- start-bridgehead.sh
This PR brings a new script that adds a basic auth user to the environment. Changed traefik to use environment variable instead of file
> WIP: Feature/bd28

- lib/add_bc_user.sh
- lib/functions.sh
- lib/remove-bridgehead-units.sh
- lib/setup-bridgehead-units.sh
- lib/update-bridgehead.sh
- Added Comparison Link Generation for Gitlab
- Changed most echos to log function calls
> Ensured Logging through the Log Function

- bridgehead
- lib/functions.sh
- lib/gitpassword.sh
- lib/prerequisites.sh
- lib/update-bridgehead.sh
* Define `GIT_PASSWORD` in Vault to the current API token/password.
* The username is expected to be `bk-{SITE_ID}`.
> Allow git to fetch credentials from Vault.

- bridgehead
- lib/functions.sh
- lib/prerequisites.sh
> Support docker compose as well as docker-compose

- bbmri/docker-compose.yml
- bridgehead
- ccp/docker-compose.yml
- lib/functions.sh
- lib/setup-bridgehead-units.sh
> Put LDM Password in cleartext in /etc/bridgehead/*.local.conf

- bridgehead
- lib/functions.sh
- lib/install-bridgehead.sh
- lib/log.sh
- lib/monitoring.sh
- lib/prepare-system.sh
- lib/prerequisites.sh
- lib/uninstall-bridgehead.sh
> Facilitate installation by scripting some installation steps

- bbmri/docker-compose.yml
- ccp/docker-compose.yml
Some Sites reported issues with large log files. Due to this, i would first reduce the log level of the beam proxy.
> refactor: Removed Debug Logging from Beam Proxy

- bridgehead
- lib/functions.sh
- lib/update-bridgehead.sh
Only clean up docker images if bridgehead is actually running.
> Dont delete all docker images

- ccp/docker-compose.yml
- ccp/vars
> DKTK local spot -> focus 🥳

- bbmri/docker-compose.yml
- ccp/docker-compose.yml
- ccp/exliquid-compose.yml
Update blaze to the latest tag
> Change blaze tag to latest

- lib/prerequisites.sh
Made grep case insensitive and moved grep directly to curl, as subshell only outputed the last line of curl
> Fixed the Time Check

- README.md
This updates documentatin only.
> Zdenkas updates for Directory and Collection usage

- bridgehead
- lib/functions.sh
- lib/monitoring.sh
- lib/prerequisites.sh
- lib/update-bridgehead.sh
Currently the config allows to use the user and password of a proxy as var or encoded in the url. The added function provides a possibility to cover both use cases
> Added proxy user + pw detection

- README.md
Added this information because many sites have asked about it.
> Information about loading data into the Bridgehead's FHIR store

- bbmri/modules/dnpm-compose.yml
- ccp/modules/dnpm-compose.yml
- minimal/modules/dnpm-compose.yml
> Add dnpm echo to dnpm-compose

- ccp/docker-compose.yml
- ccp/modules/datashield-compose.yml
- ccp/modules/datashield-setup.sh
- ccp/modules/teiler-setup.sh
- ccp/vars
- lib/functions.sh
@patrickskowronekdkfz and I refactored some stuff what do you think?
> refactor: Move vars to their setup files

- ccp/docker-compose.yml
Updating Focus to 0.4.2. Adds new Measure for DKTK
> Update focus to 0.4.2

- ccp/docker-compose.yml
Dependency for https://github.com/samply/lens/pull/85
> update: dktk focus to 0.4.4

- bbmri/modules/gbn-setup.sh
This PR should be merged at the late on 17.04 and can be reverted at the 19.04
> GBN maintenance mode

- bbmri/modules/gbn-setup.sh
> Revert "GBN maintenance mode"

- ccp/docker-compose.yml
This will switch the ccp project to the focus tag depending of environment.
> switch focus of ccp to tag

- minimal/docker-compose.yml
This is related to the update for the bridgehead-landingpage
https://github.com/samply/bridgehead-landingpage/pull/1
> Added env to landing-page

- bridgehead
> export ENVIRONMENT

- bridgehead
... to avoid errors
follow-up to #203
> Don't repeat definition of ENVIRONMENT var

- ccp/modules/datashield-setup.sh
- ccp/modules/datashield-sites.json
This was already merged into develop in #199 but as we are probably not merging develop any time soon I would like to merge it to main.
> feat: Configure beam-connect to trust ds-orchestrator beam proxy

- ccp/docker-compose.yml
- ccp/modules/fhir2sql-setup.sh
Add and set FOCUS_ENDPOINT_TYPE env variable depending on whether fhir2sql is active or not.
> add and set FOCUS_ENDPOINT_TYPE

- ccp/modules/fhir2sql-compose.yml
Please check if this actually starts up with this config
> fix(fhir2sql): add the postgres connection string to focus

- ccp/modules/exporter-compose.yml
Merge must be coordinated with focus merge https://github.com/samply/focus/pull/191
> renamed exporter API key to EXPORTER_API_KEY

- bridgehead
- versions/prod
- versions/test
I did not change any explicit versions yet. IMO that should happen in future PRs and we should focus on if this is the approach we want to go for.
Also added some docs for non bridgehead magicians.
So I guess closes #166
> feat: unify version handeling

- modules/transfair-compose.yml
CC https://github.com/samply/transFAIR/pull/25
> chore(transfair): add new gw option

- modules/transfair-compose.yml
CC https://github.com/samply/transFAIR/pull/28
> chore(transfair): add option to disable tls verification

- modules/transfair-compose.yml
CC https://github.com/samply/transFAIR/pull/30
> chore(transfair): update transfair config

- modules/transfair-compose.yml
CC https://github.com/samply/transFAIR/pull/43
> fix: adapt to transfair cli changes

- modules/transfair-compose.yml
CC https://github.com/samply/transFAIR/pull/44
> chore: add more options to transfair
