samply/bridgehead

lib/prerequisites.sh

* [Ask for correct SITE_NAME variable in error message.](https://github.com/samply/bridgehead/commit/821eebe8c690f3c1c242735304c15ec511e785a3)
* [Make TLS certificate generation non-interactively, and make certificates valid for a longer time.](https://github.com/samply/bridgehead/commit/5ddca3d9f4d21340dc69fc27575b37334000f582)

Some small fixes (see description)

---

lib/update-bridgehead.sh

Check for Github is necessary. Bitbucket Server doesn't support commit based diffs for whole repositories [refer to this as source](https://community.atlassian.com/t5/Bitbucket-questions/BitBucket-4-14-diff-between-any-two-commits/qaq-p/632974).
Later we could check how to generate Gitlab or Bitbucket.org diffs.

Added Link to Git Diff for Github Repositories to Bridgehead Update

---

lib/functions.sh

This flag is intended for usage in all docker images. It will be exposed to their environment by the bridgehead start command.

Added Environment Flag to differ between Test- and Productionsystem

---

ccp/docker-compose.yml

This fixes the issue with incorrect specimen response. The blaze data should be persisted as volume blaze-data is configured, so no reimport necessary. 
After merge all bridgeheads should pull the update at the start of the next hour.

Updated Blaze from v0.17 -> v0.18

---

bbmri/docker-compose.yml

Original indent was one space, should have been 2 spaces, otherwise you get parse errors.

Correcting landing page indent

---

lib/update-bridgehead.sh

This is to automatically switch all Bridgeheads from the falsely named branch `feature/samplyBeam` to the `main` branch.

Switch branch to main

---

bridgehead
lib/functions.sh

With this, bridgeheads will switch back to the correct blaze volumes.

hotfix: Switch to old Project Name

---

snap/docker-compose.yml

This is no longer required as it is now defined in the image itself, see https://github.com/samply/bridgehead-forward-proxy/pull/9

Remove SIGKILL for forward-proxy

---

ccp/modules/id-management-setup.sh

The openssl command rsautl, used to create deterministic but secret passwords, was deprecated in openssl version 3.0. This PR changes to the new syntax.

Replace deprecated openssl command

---

bridgehead

With the new behaviour of Beam-Enroll to also display the CSR of exsisting private keys, it is preferrable to remove the "abort on existing private key" check.

Rely on beam-enroll message for existing key

---

lib/monitoring.sh

I need a mechanism to reduce waiting time for sites that have connection issues. Otherwise it takes multiple minutes for each bridgehead restart depending on the default timeout duration

add max-time for curl monitoring

---

ccp/modules/datashield-compose.yml
ccp/modules/datashield-setup.sh

Changes:
- Opal certs get generated and read at `/etc/bridgehead/trusted-ca-certs`
- Beam connect actually uses the cert know
- This uses beam-connect:fix-connect which is a WIP branch that will at some point be merged into no-auth which is replicated by harbor

Make certs work with beam-connect

---

ccp/modules/id-management-compose.yml

Otherwise, the id-manager will always redirect to http instead of https.

Ensure Id Management redirects with SSL

---

lib/prepare-system.sh

Allow to provide the only two variables that are requested by the BK admin on installation via env variables.
Please confirm:

Allow to automate installation

---

bbmri/modules/dnpm-compose.yml
ccp/modules/dnpm-compose.yml
minimal/modules/dnpm-compose.yml

All required features for DNPM have been integrated in Beam-Connect's `develop` branch, so that no special tag is required anymore.

Use beam-connect:develop for DNPM

---

bbmri/modules/dnpm-compose.yml
ccp/modules/dnpm-compose.yml
minimal/modules/dnpm-compose.yml

Apparently, for some combinations of docker-compose and bash enforcing a string value in the `NO_AUTH` parameter is necessary for successful startup of beam-connect.

Fix dnpm connect env, from bool to string

---

ccp/modules/datashield-mappings.json
ccp/modules/datashield-setup.sh

The central sites need to be filled in obviously. I don't know which sites take part in this opal business.
Just replace `$SITE_ID` with the site id of the site for all the sites.

Auto generate mappings

---

lib/update-bridgehead.sh

Even if the repository URL uses HTTPS, git uses the http.proxy configuration if the *proxy* is reachable via HTTP.

git requires http proxy config even vor https connections

---

ccp/docker-compose.yml

Enable statistical obfuscation for CCP query results. Chosen Parameters:
* Epsilon = 0.28
* Sensitivity Patients/Specimen/Diagnosis/Procedures/Medication Statements= 1/20/3/1.7/2.1
* Don't obfuscate real zeros
* Display 10 for 0 < count < 10
* Round to the next 10s
Required for merging:

Enable obfuscation for ccp queries

---

minimal/modules/nngm-compose.yml
minimal/modules/nngm-setup.sh

For running a combined DNPM and nNGM bridgehead it is required to use the nngm module out of the minimal project.

Add nngm module to minimal project

---

ccp/modules/dnpm-compose.yml
ccp/modules/dnpm-setup.sh
minimal/modules/dnpm-compose.yml
minimal/modules/dnpm-setup.sh

Some sites need to add additional no_proxy targets to the dnpm-beam-connect service.
This PR introduces an optional `DNPM_NO_PROXY` config variable, which, if set, adds the string (with an prepended comma) to the already existing dnpm-beam-connect no_proxy environment.

Add DNPM_NO_PROXY configuration option

---

ccp/modules/dnpm-node-compose.yml
ccp/modules/dnpm-node-setup.sh
minimal/modules/dnpm-node-compose.yml
minimal/modules/dnpm-node-setup.sh

Using the `DNPM_SYNTH_NUM` environment variable the number of rendomly generated synthetic data in the dnpm_backend can be controlled. If not present or empty, it defaults to 0 generated random entries.
I added some formatting change to the setup.sh files, which were not in splittable git hunks, sorry :(

Create env to control dnpm synthetic data generation

---

lib/prerequisites.sh

Minimal bridgeheads are not necessarily connected to a beam communication infrastructure, hence the private key is not necessarily created. Additionally, the Broker for time checks might not be configured, nor the time check necessary. 
This PR checks if the project name is `minimal` and skips those tests if true. Currently, the install and the starting processes exit at the checks.

Don't test clock skew and private key existance for minimal bridgeheads

---

ccp/docker-compose.yml

Updates the ccp focus to version 0.4.1. This does obfuscate the histology counting.

Updated ccp focus to 0.4.1

---

bbmri/docker-compose.yml
bridgehead
ccp/docker-compose.yml
lib/functions.sh

This will adjust the memory used by blaze on the different servers. The bridgehead start script reads the available memory from /proc/meminfo and calculates the amount to give to blaze in Megabyte. With this, blaze should receive approxymately one half of the RAM available to the systems, as one quarter is used for each, the java heap size and the db cache.
I tested it locally in wsl, where the amount used by blaze was reduced from 4G to 1951m. It would be good if someone could test it on a server.

Optimize memory usage of Blaze

---

lib/functions.sh

Bash 4.2 is used by CentOS and other Redhead based distros I think. The main branch did not work on serv-05 because of this.
You can try this out with docker:
```bash
docker run -it bash
echo $(("12"/4)) # Works
exit
docker run -it bash:4.2
echo $(("12"/4)) # Does not work
```

fix: Make math work on bash 4.2

---

bridgehead

Still not quite sure as to why they got stale.
Never the less this will make sure they get killed if active.

fix: Kill stale secret-sync instances

---

lib/functions.sh

fix: Generate public oidc client when there is no private client

---

ccp/modules/id-management-compose.yml

Before this PR, the Mainzelliste would always respond with http instead of https then referring to it self in urls.

Ensure Mainzelliste returns SSL in Responses

---

README.md
bridgehead
lib/functions.sh

I added `-a` as a default option for journalctl as it preserves the colors and fixes an issue where docker logs would only show up as `[blob data x kb]`. I dont think it has any downside

feat: Add logs command for journalctl

---

bbmri/docker-compose.yml
ccp/docker-compose.yml

The 0.28 release is not downgradeable, therefore switching again to 0.28

fix: set blaze to version 0.28

---

ccp/modules/datashield-compose.yml

The `PathPrefix` filter was never intended for 2 args I think and it seems it has become a hard error in a recent traefik version rendering the rout unavailable.

fix: Fix traefik label for oauth2 redirect

---

README.md

Recommendation for standalone Bridgehead

---

README.md
bbmri/modules/directory-sync-compose.yml

There were problems with the passing of environment variables from bbmri.conf to the Directory synce container:
* The Directory password variable was misspellt.
* Some useful variables were missing.
Additionally, a delay was added before launching Directory sync, to give Blaze time to start up.

Fixed environment variable passing for Directory sync

---

ccp/modules/id-management-compose.yml

This PR introduces a new way for Authentication in CCP ID-Management. Instead of Samply Auth, we use Keycloak as a provider. For this we added oauth2-proxy to handle the authentication and refactored the implementation in MagicPL to only do the check of the users access token and necessary groups. Unfortunately, i couldn't get it to work that we only have one installation of the oauth2-proxy running in the bridgehead. DataSHIELD still needs it's own, as both idm and datashield require a specific group for access and i was not able to separate this only in the labels.
Things we need to do before merging:

Switch ID-Management to Keycloak from Samply.Auth

---

ccp/modules/id-management-compose.yml

Otherwise traefik will match the route with the one specified in datashield-compose.yml

fix: specify host for id-management login

---

ccp/modules/datashield-compose.yml
ccp/modules/id-management-compose.yml

Before this change CentraXX was redirected to the central login servers then interacting with the id-management

Allow Usage of Centraxx Interface without login

---

bbmri/docker-compose.yml
ccp/docker-compose.yml
lib/functions.sh

This PR sets a calculated CQL cache value to Blaze. It's been tested locally and on one bridgehead and the performance gains are ok to good. I didn't test if the amount of cache if too low or too much, I think this needs to be tested in the long term.

feat: added blaze cql cache

---

.github/scripts/rename_inactive_branches.py
.github/workflows/rename-inactive-branches.yml

The goal is to automatically archive unused branches (rename to "archived/..." after 365 days of no commit).
Actual code execution is [commented](https://github.com/samply/bridgehead/pull/238/files#diff-d9915e153125f24788b5dfc941e10c009a508dee3bf93ecf09ded01ab27189afR31-R32) (since I don't want to trigger the process until approved) 
These branches would be affected:
https://github.com/samply/bridgehead/actions/runs/11340581646/job/31537252148#step:5:10
Will delete this code once ready for merging

feat: add auto archiving action

---

ccp/modules/exporter-compose.yml

Add exporter configuration in focus for CCP in order to accept queries trough beam from central project manager (data science orchestrator)

Add exporter configuration to focus

---

ccp/modules/id-management-compose.yml

This PR change the image url to verbis cache.

fix: use verbis cache image instead of docker-hub

---

lib/update-bridgehead.sh

This PR fixes an issues with reporting the git access tokens via update

fix: remove credentials from git remote, if update fails

---

ccp/modules/nngm-compose.yml
ccp/modules/obds2fhir-rest-compose.yml
kr/modules/obds2fhir-rest-compose.yml
minimal/modules/nngm-compose.yml

I dont know if there is a good reason for it for the secondary blaze @PierreDelpy

fix: remove `restart: always` in compose files

---

ccp/modules/id-management-compose.yml

This PR fixes the environment variable of the CCP-PPI, where the SITE_NAME is not consistent with the IDMANAGEMENT_FRIENDLY_ID

fix: changed ccp_ppi to use IDMANAGEMENT_FRIENDLY_ID instead of SITE_NAME

---

ccp/modules/dnpm-node-compose.yml
minimal/modules/dnpm-node-compose.yml

This is one half of the changes we talked about last week: Securing the ETL endpoints with basic auth and denying access to the p2p api for external hosts.
I did not test that the variable actually gets inserted, I'm a bit confused about the shell scripts. But replacing `${ETL_PASSWD}` with the actual auth data works.
For ETL to work, this needs an ETL processor with support for basic auth. [This has been merged](https://github.com/pcvolkmer/etl-processor/pull/75), but is not yet part of any release.
@Threated

dnpm: Secure endpoints for ETL and p2p communications

---

minimal/modules/dnpm-node-compose.yml

When a OIDC provider is configured, you'll get redirected to authup by Keycloak which redirects you to the DNPM:DIP. 
Currently the url looks like this:
`https://myserver/authup//someurl`
and produces an error. Manually removing the additional `/` fixes the issue.

fix authup redirect

---

README.md

As described in #263, the link to the official Docker Hub URL list changed, leading to a 404 error  with the current readme. This PR links to the new site.

Fixed Docker Hub URL list link

---

lib/functions.sh

fixes serv-05
Really don't know why this only sourced the first file.
I guess it was a CentOS specialty.

fix: properly load oidc secrets

---

ccp/modules/dnpm-compose.yml
ccp/modules/dnpm-node-compose.yml
ccp/modules/dnpm-node-setup.sh
minimal/docker-compose.yml
minimal/modules/dnpm-central-targets.json
minimal/modules/dnpm-compose.yml
minimal/modules/dnpm-node-compose.yml
minimal/modules/dnpm-node-setup.sh

The files under `ccp/` are only copies of the files under `minimal/`.
I removed the `/api` path from traefik as it was conflicting with dnpms backend path.
I have never seen anyone of us actually use the traefik frontend but I think `/dashboard` is a better name anyway but if we want to keep it that way we might be able to do a bit of traefik path rewriting to make it work without this change.
Maybe we can even backport this to the `dnpm-extra-broker` branch?

feat: migrate to new dnpm:dip node

---

README.md

With the recent change of the default branch to develop, new bridgehead installations will default upon cloning to the develop branch. With adjusting the instructions like this, git will clone the main branch.

docs: explicitly clone main branch

---

lib/functions.sh
lib/update-bridgehead.sh

This is to anticipate an upcoming change in Secret Sync that will allow it to support multiple GitLab servers, e.g. verbis GitLab and BBMRI GitLab.
I moved things to a function and added the case statement. The only thing I changed in the code that was there before is this line:
```bash
-e SECRET_DEFINITIONS=GitLabProjectAccessToken:BRIDGEHEAD_CONFIG_REPO_TOKEN:$gitlab \
```

Send the origin of /etc/bridgehead repo to Secret Sync

---

bbmri/docker-compose.yml
cce/docker-compose.yml
ccp/docker-compose.yml
ccp/modules/blaze-secondary-compose.yml
dhki/docker-compose.yml
itcc/docker-compose.yml
kr/docker-compose.yml
modules/transfair-compose.yml
versions/prod
versions/test

Seems like there are no breaking changes https://github.com/samply/blaze/releases/tag/v0.32.0

chore: unify blaze versioning and upgrade to 0.32

---

lib/functions.sh
lib/gitlab-token-helper.sh

`/var/cache/bridgehead` did not exist on some bridgeheads, probably because they were installed before https://github.com/samply/bridgehead/blob/7365be3e7bf4d6ab7a9dcc4d5de40c8a13e5a8dc/lib/prepare-system.sh#L107 was added.
This PR uses a boot-scoped temporary directory to avoid such issues in the future.
The previous implementation kind of caused a mess on some servers because the Docker daemon created `/var/cache/bridgehead/secrets/gitlab_token` as a directory with owner `root:root`. Would be kind of difficult to clean up as most scripts run as `bridgehead` user.

Use tmp directory for secret sync cache

---

ccp/modules/teiler-compose.yml

**Summary:**
This pull request introduces a small configuration update for Teiler to support the new Docker images. These new images embed external libraries, allowing Teiler to run without requiring internet access.
**Compatibility:**
The change is fully backward compatible with previous versions of the old Teiler Docker images, so merging into main should not cause any issues.

[Hotfix] Teiler without Internet

---

ccp/modules/teiler-compose.yml
kr/modules/teiler-compose.yml

Small configuration update for the latest version of the Teiler Backend.
The changes are backward compatible and apply to both CCP and KR.

Update some Teiler Backend variables

---

README.md

In the Exporter section of the Readme, one codeblock was left open.
This commit fixes this.

fix: close Exporter code block in readme

---

ccp/modules/dnpm-node-compose.yml
minimal/modules/dnpm-node-compose.yml

I removed the tag option for now as it does not have any other tags and I don't want to break deployments that use a custom tag

feat(dnpm): change to new `api-gateway` image

---

ccp/docker-compose.yml

Previously when this var was empty focus treated it as a project `""` which is of course not intended. With this env var syntax docker only passes the env var when set. We already use this syntax in transfair and other compose files here. I tested this locally and it works

fix: only pass CQL_PROJECTS_ENABLED to focus if set
